steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/simple-http:${_IMAGE_TAG}', '-t', 'gcr.io/$PROJECT_ID/simple-http:latest', '.' ]
logsBucket: gs://jjzeng-cloudbuild-logs
images:
- 'gcr.io/$PROJECT_ID/simple-http'
