apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: simple-http # The name of the app
  namespace: default # The namespace the app will use
spec:
  template:
    spec:
      containers:
        - image: gcr.io/jjzeng-knative-dev/simple-http:latest
          env:
            - name: BUILD
              value: "sidecar-inject"
